name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.19

    - name: Build
      run: |
        go get ./...
        go build -v ./... -o vib

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: vib
        path: vib